version: '3.6'

volumes:
  lfr-database:

services:

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - lfr-database:/var/lib/mysql
