version: '3.6'

volumes:
  lfr-document-library:
  lfr-database:
  lfr-modules:
  lfr-war:

services:

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8 --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - lfr-database:/var/lib/mysql

  liferay:
    image: egf/liferay
    build: ./
    environment:
      - LIFERAY_JVM_OPTS=-server -Xms8g -Xmx24g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Delasticsearch.protocol=http -Delasticsearch.host=search -Delasticsearch.port=9200 -Delasticsearch.operation.mode=REMOTE -Delasticsearch.cluster.name=LiferayElasticsearchCluster -Delasticsearch.production.enabled=false -Dtomcat.maxThreads=300 -Dtomcat.minSpareThreads=50 -Dtomcat.maxConnections=16384 -Duser.timezone=GMT-3
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=root
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_NAME=EGF
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_WEB_PERIOD_ID=egf.com
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_LOCALE=pt_PT
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_TIME_PERIOD_ZONE=GMT-3
      - LIFERAY_COMPANY_PERIOD_LOGIN_PERIOD_PREPOPULATE_PERIOD_DOMAIN=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_AUTH_PERIOD_TYPE=emailAddress
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_SEND_PERIOD_PASSWORD_PERIOD_RESET_PERIOD_LINK=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PRIVATE_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_AUTO_PERIOD_CREATE=false
      - LIFERAY_LAYOUT_PERIOD_USER_PERIOD_PUBLIC_PERIOD_LAYOUTS_PERIOD_ENABLED=false
      - LIFERAY_BLOGS_PERIOD_PINGBACK_PERIOD_ENABLED=false
      - LIFERAY_BLOGS_PERIOD_PING_PERIOD_GOOGLE_PERIOD_ENABLED=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SERVLET_PERIOD_FILTERS_PERIOD_SSO_PERIOD_CAS_PERIOD__UPPERCASEC__UPPERCASEA__UPPERCASES__UPPERCASEF_ILTER=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SERVLET_PERIOD_FILTERS_PERIOD_SSO_PERIOD_NTLM_PERIOD__UPPERCASEN_TLM_UPPERCASEF_ILTER=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SERVLET_PERIOD_FILTERS_PERIOD_SSO_PERIOD_NTLM_PERIOD__UPPERCASEN_TLM_UPPERCASEP_OST_UPPERCASEF_ILTER=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SERVLET_PERIOD_FILTERS_PERIOD_SSO_PERIOD_OPENSSO_PERIOD__UPPERCASEO_PEN_UPPERCASES__UPPERCASES__UPPERCASEO__UPPERCASEF_ILTER=false
      - LIFERAY_COM_PERIOD_LIFERAY_PERIOD_PORTAL_PERIOD_SHAREPOINT_PERIOD__UPPERCASES_HAREPOINT_UPPERCASEF_ILTER=false
      - LIFERAY_LOCALES=en_US,pt_PT
      - LIFERAY_LOCALES_PERIOD_ENABLED=en_US,pt_PT
      - LIFERAY_SESSION_PERIOD_TRACKER_PERIOD_MEMORY_PERIOD_ENABLED=false
      - LIFERAY_HIBERNATE_PERIOD_JDBC_PERIOD_BATCH_UNDERLINE_SIZE=200
      - LIFERAY_BUFFERED_PERIOD_INCREMENT_PERIOD_STANDBY_PERIOD_QUEUE_PERIOD_THRESHOLD=10000
      - LIFERAY_BUFFERED_PERIOD_INCREMENT_PERIOD_STANDBY_PERIOD_TIME_PERIOD_UPPER_PERIOD_LIMIT=60
      - LIFERAY_COUNTER_PERIOD_INCREMENT=5000
      - LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED=false
      - LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE=true
      - LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL=com.liferay.portal.store.file.system.AdvancedFileSystemStore
      - LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE=domain
      - LIFERAY_JSONWS_PERIOD_WEB_PERIOD_SERVICE_PERIOD_API_PERIOD_DISCOVERABLE=false
      - LIFERAY_LAYOUT_PERIOD_FRIENDLY_PERIOD_URL_PERIOD_PAGE_PERIOD_NOT_PERIOD_FOUND=/page404
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - lfr-document-library:/opt/liferay/data/document_library
      - ./liferay/liferay-files:/mnt/liferay/files
      - lfr-modules:/opt/liferay/osgi/modules
      - lfr-war:/opt/liferay/osgi/war
      - ./liferay/deploy:/mnt/liferay/deploy
    depends_on:
      - database
      - search

  search:
    image: egf/elasticsearch
    build: ./elasticsearch/
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
